/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import logic.DataInserert;
import logic.Setup;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author Alessandro
 */
public class DataInsertForm extends javax.swing.JFrame {

    /**
     * Creates new form DataInsertForm
     */
    public DataInsertForm() {
        initComponents();
        
        this.dataInsert = new DataInserert();
        this.setup = new Setup();
        
        // initTitleFinanceName();
    }

    private void initTitleFinanceName() {
//          INSERIRE CASO IN CUI NON C'E' PIU' IL FILE!!        
        BufferedReader buffer = null;
        try {
            buffer = new BufferedReader(new FileReader(setup.getDatabaseAbsolutePath()));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(DataInsertForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.financeTitleBox.addItem('-');
        
        String line = null;
        JSONObject obj = null;
        while (true) {
            try {
                line = buffer.readLine();
            } catch (IOException ex) {
                Logger.getLogger(DataInsertForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if (line != null) {
                try {
                    obj = new JSONObject(line);
                    this.financeTitleBox.addItem(obj.getString(DataInserert.NAME_KEY));
                } catch (JSONException ex) {
                    Logger.getLogger(DataInsertForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                break;
            }            
        }        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ok = new javax.swing.JButton();
        existFinanceTitle = new javax.swing.JRadioButton();
        titleNameMsg = new javax.swing.JLabel();
        titleFinanceText = new javax.swing.JTextField();
        quotationMsg = new javax.swing.JLabel();
        quotationText = new javax.swing.JTextField();
        minimumMsg = new javax.swing.JLabel();
        minimumText = new javax.swing.JTextField();
        vomunesMsg = new javax.swing.JLabel();
        volumesText = new javax.swing.JTextField();
        financeTitleBox = new javax.swing.JComboBox();
        maximumMsg = new javax.swing.JLabel();
        maximumText = new javax.swing.JTextField();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Inserire dati");

        ok.setText("Ok");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        existFinanceTitle.setText("Titolo finenziario già esistente");

        titleNameMsg.setText("Titolo finanziario:");

        titleFinanceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFinanceTextActionPerformed(evt);
            }
        });

        quotationMsg.setText("Quotazione:");

        quotationText.setText("jTextField1");

        minimumMsg.setText("Minimo:");

        minimumText.setText("jTextField1");

        vomunesMsg.setText("Volumi:");

        volumesText.setText("jTextField1");

        maximumMsg.setText("Massimo:");

        maximumText.setText("jTextField1");

        jMenu1.setText("File");

        exitMenu.setText("Esci");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        menu.add(jMenu1);

        jMenu2.setText("Edit");
        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 493, Short.MAX_VALUE)
                        .addComponent(ok))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minimumMsg)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleNameMsg)
                                    .addComponent(quotationMsg))
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(existFinanceTitle)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(titleFinanceText)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(minimumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(quotationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addGap(70, 70, 70)
                                .addComponent(financeTitleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vomunesMsg)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(maximumMsg)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(maximumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(130, 130, 130)
                                    .addComponent(volumesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(existFinanceTitle)
                    .addComponent(financeTitleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleNameMsg)
                            .addComponent(titleFinanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(quotationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(quotationMsg))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minimumMsg)
                    .addComponent(minimumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maximumMsg)
                    .addComponent(maximumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vomunesMsg)
                    .addComponent(volumesText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Programmazione dell'esento del tasto "Ok" per salvare i dati nel database.
     *  
     * @param evt 
     */
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
      this.dataInsert.addData(this.titleFinanceText, this.quotationText, this.minimumText, this.maximumText, this.volumesText);
    }//GEN-LAST:event_okActionPerformed

    /**
     * Uscita della form.
     * 
     * @param evt 
     */
    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuActionPerformed

    private void titleFinanceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFinanceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFinanceTextActionPerformed

    private DataInserert dataInsert;
    private Setup setup;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton existFinanceTitle;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JComboBox financeTitleBox;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel maximumMsg;
    private javax.swing.JTextField maximumText;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel minimumMsg;
    private javax.swing.JTextField minimumText;
    private javax.swing.JButton ok;
    private javax.swing.JLabel quotationMsg;
    private javax.swing.JTextField quotationText;
    private javax.swing.JTextField titleFinanceText;
    private javax.swing.JLabel titleNameMsg;
    private javax.swing.JTextField volumesText;
    private javax.swing.JLabel vomunesMsg;
    // End of variables declaration//GEN-END:variables
}
