/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import logic.Setup;

/**
 *
 * @author Alessandro
 */
public class FinanceData extends javax.swing.JFrame {
    private Setup setup;
    
    
    /**
     * Costruttore particolare della classe.
     */
    public FinanceData() {
        this.setLocation(600, 300);
        this.setSize(200, 300);
        
        initComponents();
        
        this.setup = new Setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitFile = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        impostationEdit = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FinanceData");

        fileMenu.setText("File");

        exitFile.setText("Esci");
        fileMenu.add(exitFile);

        menuBar.add(fileMenu);

        editMenu.setText("Modifica");

        impostationEdit.setText("Impostazioni");
        impostationEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                impostationEditActionPerformed(evt);
            }
        });
        editMenu.add(impostationEdit);

        jMenuItem1.setText("Inserire dati");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        editMenu.add(jMenuItem1);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Metodo per la programmazione del tasto Impostazioni (Modifica -> Impostazioni).
     * 
     * @param evt 
     */
    private void impostationEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_impostationEditActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Impostation().setVisible(true);
            }
        });
    }//GEN-LAST:event_impostationEditActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataInsertForm().setVisible(true);
            }
        });
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitFile;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem impostationEdit;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
